baseurl: https://suyogs.com
languageCode: en-us
theme: 
    - hugo-simple
# paginate: 5
pagination:
    pagerSize: 50
title: Suyog's Blog

# Doing this makes some stuff work better if testing out with file:// urls
# but it still shows directories that way; might as well just use
# cd ./public && python3 -m http.server 2133
# relativeURLs: true

# Change it to your Disqus shortname before using
disqusShortname: suyogs-blog

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    hideMadeWithLine: true
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2019
        customText:

    dateFormat: Jan 02, 2006
        # published: Jan 02, 2006
        # lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 
        subtitle: Chronotale. Ex-Meta, Ex-Oscar software engineer.
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

copyright: © 2019-2025 Suyog Sonwalkar

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
### The hugo documention on this is here: https://gohugo.io/variables/menus/
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: home
        - identifier: about
          name: About
          url: /about/
          weight: -90
          params:
            icon: user
        # - identifier: archives
        #   name: Archives
        #   url: /archives/
        #   weight: -70
        #   params:
        #     icon: archives
        # - identifier: search
        #   name: Search
        #   url: /search/
        #   weight: -70
        #   params:
        #     icon: search
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/flux159/hugoblog
          params:
            icon: brand-github
            
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/flux159
          params:
            icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
